---
- name: Deploy tradepr
  hosts: tradepr
  vars:
    proj_name: tradepr-project
    database_user: "{{ proj_name }}"
    database_name: "{{ proj_name }}"
    locale: en_US.UTF-8
  vars_files:
    - secrets.yml
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - python-pip
        - python-virtualenv
        - python-psycopg2
        - python-apt
        - postgresql-9.3
        - unzip
    - name: add repo for unstable python
      apt_repository: repo='ppa:pythonxy/pythonxy-devel'
      sudo: True
    - name: install unstable pandas
      apt: pkg=python-pandas update_cache=yes cache_valid_time=3600
      sudo: True
    - name: pip requirements
      pip: name={{ item }}
      sudo: True
      with_items:
        - sqlalchemy
    - name: create a database user
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ db_pass }}"
      sudo: True
      sudo_user: postgres
    - name: create the database
      postgresql_db:
        name: "{{ database_name }}"
        owner: "{{ database_user }}"
        encoding: UTF8
        lc_ctype: "{{ locale }}"
        lc_collate: "{{ locale }}"
        template: template0
      sudo: True
      sudo_user: postgres
    - name: import csv files
      import_zip_csv:
        dbname: "{{ database_name }}"
        dbuser: "{{ database_user }}"
        dbpassword: "{{ db_pass }}"
        zipurl: http://www.estadisticas.gobierno.pr/iepr/LinkClick.aspx?fileticket=JVyYmIHqbqc%3d&tabid=200
      sudo: True
      sudo_user: postgres
