---
galaxy_info:
  author: Nick Janetakis
  description: Install a bare bones version of postgresql.
  company: 
  license: license (MIT)
  min_ansible_version: 1.5

  platforms:
  - name: Ubuntu
    versions:
    - all

  - name: Debian
    versions:
    - all

  categories:
  - database
  - database:sql

dependencies: []
